## Data Analyst / Data Scientist:

- Data = Won't always be in csv, Excel...
- Data Comes from API's
- Dashboards -> Refresh data using API's
- Design data pripelines using API's

In [ ]:
'''
## Weather Updates
- Smart phones = Apple, Samsung, 1+
- Watches = Samsung, Mi,.....
- Clocks = Titan,/..
- Laptops = Apple, Dell,
- TV's = Sony, Samsung
- Automobile = Ather, TVS, OLA
'''

#  Weather API's

In [ ]:
# API = Postman

# API(Application Programming Interface)
An API (Application Programming Interface) is a toolbox 🛠️ that allows different software applications to communicate and share data with each other. It’s like a bridge 🌉 that connects two systems, enabling them to interact without needing to know how the other works internally.

**What is an API?**

- API as a waiter in the Restaurant

- Customer(The user) = orders the food
- The Chef(The Database/ Server) = Prepare the food
- The Waiter (API)

## GOAL: The user wants to check the weather in their city.

1. Frontend (WebPage/ Android Application)
- The User enters the city name and Clicks on Get weather Button.

2. API Request to weather server/ database.

3. This API Request will be processed and a response will be generated.

4. The Weather server sends the response to the API

5. The API delivers the response to the user(BY Udating in the Application)

In [ ]:
# https://www.google.com

# RESTFUL API
📌 **What Does "RESTful" Mean?**

REST (Representational State Transfer) is a set of rules that make APIs simple, fast, and easy to use.
When an API follows these rules, we call it RESTful API.'

- Everything is considered as a resource.
- Stateless memory
- HTTPs Protocol = Diff methods

In [ ]:
'''
# Everything is considered as a resource.(Like employess, /yashas,/students  )

Base_URL = www.almabetter.com

employee = www.almabetter.com/employess
emplyee yashas = www.almabetter.com/employee/yashas
Student = www.almabetter.com/students
'''

### **HTTP Methods and CRUD Operations**
**HTTP Methods:**

1. **GET:** Retrieves data from the server.
2. **POST:** Sends data to the server to create a new resource.
3. **PUT:** Updates or replaces an entire resource.
4. **PATCH:** Updates specific fields of a resource.
5. **DELETE:** Deletes a resource from the server.

In [ ]:
# HTTP = Hypertext Transfer Protocol
# HTTPs= Secured Hypertext Transfer Protocol (Data is Encrypted 128K)

In [ ]:
import requests
import pandas as pd

In [ ]:
BASE_URL = "http://4.186.26.27:8787" #Home Page = Starting point of an API

# GET

Purpose : Retrieves data from the server.

When you want to fetch some information, such as a list of employess, lise of movies, weater data.

**Example:**

**Request:** = Get /movies

**Response** = A list of movie names

In [ ]:
'''
Response 200 = Request is Successful
Response 404 = Resource is not found
Response 300 = Investigate further

'''

In [ ]:
# Get all the employee details from the BASE_URL

response = requests.get("http://4.186.26.27:8787/employees")
response.json()

ConnectionError: HTTPConnectionPool(host='4.186.26.27', port=8787): Max retries exceeded with url: /employees (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79241b8bd730>: Failed to establish a new connection: [Errno 111] Connection refused'))

In [ ]:
# Get all the employee details from the BASE_URL

response = requests.get("http://4.186.26.27:8787/employees")
pd.json_normalize(response.json())

ConnectionError: HTTPConnectionPool(host='4.186.26.27', port=8787): Max retries exceeded with url: /employees (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79241b8be5a0>: Failed to establish a new connection: [Errno 111] Connection refused'))

In [ ]:
# Get the details of employee ID 2 from the BASE_URL

response = requests.get("http://4.186.26.27:8787/employees/2")
pd.json_normalize(response.json())

   age department  gender  id  name  salary
0   23  marketing  female   2  jane  600000

In [ ]:
response = requests.get("http://4.186.26.27:8787/employees/20")
pd.json_normalize(response.json())

                error
0  Employee not found

In [ ]:
response = requests.get("http://4.186.26.27:8787/employees")
response.json()

[{'age': 20,
  'department': 'hr',
  'gender': 'male',
  'id': 1,
  'name': 'john',
  'salary': 500000},
 {'age': 23,
  'department': 'marketing',
  'gender': 'female',
  'id': 2,
  'name': 'jane',
  'salary': 600000},
 {'age': 23,
  'department': 'it',
  'gender': 'male',
  'id': 3,
  'name': 'joey',
  'salary': 300000},
 {'age': 25,
  'department': 'hr',
  'gender': 'female',
  'id': 4,
  'name': 'sarah',
  'salary': 450000},
 {'age': 28,
  'department': 'hr',
  'gender': 'male',
  'id': 5,
  'name': 'rose',
  'salary': 700000},
 {'age': 29,
  'department': 'finance',
  'gender': 'male',
  'id': 6,
  'name': 'bing',
  'salary': 800000},
 {'age': 41,
  'department': 'it',
  'gender': 'female',
  'id': 7,
  'name': 'rach',
  'salary': 600000},
 {'age': 23,
  'department': 'marketing',
  'gender': 'female',
  'id': 8,
  'name': 'monica',
  'salary': 7000000},
 {'age': 35,
  'department': 'it',
  'gender': 'female',
  'id': 9,
  'name': 'pheebe',
  'salary': 4000000}]

# **POST📤**
Purpose: Send data to the server to create a new resource.

Use Case: When you need to add new information, such as creating a new user, uploading a photo, or submitting a form.

**Example:**

Request: POST /users

Payload: {"name": "Alice", "age": 25}

Response: Confirmation of the new user creation ✅.

Analogy: Like mailing a package 📦—you’re sending something to be added.

In [ ]:
new_employee = {
        "id": 10,
        "name": "Nasim",
        "age": 30,
        "gender": "female",
        "department": "sales",
        "salary": 900000
    }

In [ ]:
updated_data= requests.post("http://4.186.26.27:8787/employees", json= new_employee)
updated_data.json()

{'employee': {'age': 30,
  'department': 'sales',
  'gender': 'female',
  'id': 10,
  'name': 'Nasim',
  'salary': 900000},
 'message': 'Employee added'}

In [ ]:
response = requests.get("http://4.186.26.27:8787/employees")
pd.json_normalize(response.json())

   age department  gender  id    name   salary
0   20         hr    male   1    john   500000
1   23  marketing  female   2    jane   600000
2   23         it    male   3    joey   300000
3   25         hr  female   4   sarah   450000
4   28         hr    male   5    rose   700000
5   29    finance    male   6    bing   800000
6   41         it  female   7    rach   600000
7   23  marketing  female   8  monica  7000000
8   35         it  female   9  pheebe  4000000
9   30      sales  female  10   Nasim   900000

# **PUT 📝**
Purpose: Update an existing resource completely.

Use Case: When you need to modify an entire resource, such as updating a profile or replacing data.

In [ ]:
nasim_updated = {
        "id": 10,
        "name": "Nasim",
        "age": 30,
        "gender": "Male",
        "department": "sales",
        "salary": 1100000
    }

In [ ]:
updated_data = requests.put("http://4.186.26.27:8787/employees/10", json=nasim_updated )

In [ ]:
response = requests.get("http://4.186.26.27:8787/employees")
pd.json_normalize(response.json())

   age department  gender  id    name   salary
0   20         hr    male   1    john   500000
1   23  marketing  female   2    jane   600000
2   23         it    male   3    joey   300000
3   25         hr  female   4   sarah   450000
4   28         hr    male   5    rose   700000
5   29    finance    male   6    bing   800000
6   41         it  female   7    rach   600000
7   23  marketing  female   8  monica  7000000
8   35         it  female   9  pheebe  4000000
9   30      sales    Male  10   Nasim  1100000

# **PATCH** 🩹
Purpose: Partially update an existing resource.

Use Case: When you need to modify only specific fields, such as changing just the username without altering other details.

Example:

Request: PATCH /users/123

Payload: {"name": "Alice B."}

Response: Updated user data 🎯.

Analogy: Like fixing a typo ✍️ in a document.

In [ ]:
# Update the age of nasim to 26Y
new_data = {
    "age":26
}

In [ ]:
requests.patch("http://4.186.26.27:8787/employees/10", json=new_data )

In [ ]:
response = requests.get("http://4.186.26.27:8787/employees")
pd.json_normalize(response.json())

   age department  gender  id    name   salary
0   20         hr    male   1    john   500000
1   23  marketing  female   2    jane   600000
2   23         it    male   3    joey   300000
3   25         hr  female   4   sarah   450000
4   28         hr    male   5    rose   700000
5   29    finance    male   6    bing   800000
6   41         it  female   7    rach   600000
7   23  marketing  female   8  monica  7000000
8   35         it  female   9  pheebe  4000000
9   26      sales    Male  10   Nasim  1100000

In [ ]:
'''
.get , .post, .put, .patch

put = Full replacement
patch = Update a particular feature

eg:PUT = Replace he authecator file, Update the emplyee record completely

The Prob with patch:


Patch can be dangerous when

eg: Patch/employee/10
{
  'Salary':60000
}
'''

'\n.get , .post, .put, .patch\n\nput = Full replacement\npatch = Update a particular feature\n\neg:PUT = Replace he authecator file, Update the emplyee record completely \n\nThe Prob with patch:\n\n\nPatch can be dangerous when \n\neg: Patch/employee/10 \n'

# **DELETE🗑️**
Purpose: Remove a resource from the server.

Use Case: When you need to delete information, such as removing a user or deleting a file.

Example:

Request: DELETE /users/123

Response: Confirmation of deletion 🛑.

Analogy: Like throwing something away 🗑️—it’s gone.

In [ ]:
# Delete the emplyee Nasim

requests.delete("http://4.186.26.27:8787/employees/10")

In [ ]:
response = requests.get("http://4.186.26.27:8787/employees")
pd.json_normalize(response.json())

   age department  gender  id    name   salary
0   20         hr    male   1    john   500000
1   23  marketing  female   2    jane   600000
2   23         it    male   3    joey   300000
3   25         hr  female   4   sarah   450000
4   28         hr    male   5    rose   700000
5   29    finance    male   6    bing   800000
6   41         it  female   7    rach   600000
7   23  marketing  female   8  monica  7000000
8   35         it  female   9  pheebe  4000000

In [ ]:
covid_url ="https://covid-api.com/api/reports?iso=IND"

response = requests.get(covid_url)
pd.json_normalize(response.json()['data'])

,date,confirmed,deaths,recovered,confirmed_diff,deaths_diff,recovered_diff,last_update,active,active_diff,fatality_rate,region.iso,region.name,region.province,region.lat,region.long,region.cities
0,2023-03-09,10751,129,0,0,0,0,2023-03-10 04:21:03,10622,0,0.0120,IND,India,Andaman and Nicobar Islands,11.225999,92.968178,[]
1,2023-03-09,2339096,14733,0,1,0,0,2023-03-10 04:21:03,2324363,1,0.0063,IND,India,Andhra Pradesh,15.9129,79.74,[]
2,2023-03-09,66891,296,0,0,0,0,2023-03-10 04:21:03,66595,0,0.0044,IND,India,Arunachal Pradesh,27.768456,96.384277,[]
3,2023-03-09,746100,8035,0,0,0,0,2023-03-10 04:21:03,738065,0,0.0108,IND,India,Assam,26.357149,92.830441,[]
4,2023-03-09,851427,12303,0,1,0,0,2023-03-10 04:21:03,839124,1,0.0144,IND,India,Bihar,25.679658,85.60484,[]
5,2023-03-09,99370,1182,0,0,0,0,2023-03-10 04:21:03,98188,0,0.0119,IND,India,Chandigarh,30.733839,76.76827800000002,[]
6,2023-03-09,1177804,14146,0,3,0,0,2023-03-10 04:21:03,1163658,3,0.0120,IND,India,Chhattisgarh,21.264705,82.035366,[]
7,2023-03-09,2007605,26523,0,4,0,0,2023-03-10 04:21:03,1981082,4,0.0132,IND,India,Delhi,28.646519,77.10898,[]
8,2023-03-09,259167,4013,0,2,0,0,2023-03-10 04:21:03,255154,2,0.0155,IND,India,Goa,15.359682,74.057396,[]
9,2023-03-09,1277848,11046,0,30,0,0,2023-03-10 04:21:03,1266802,30,0.0086,IND,India,Gujarat,22.694884,71.590923,[]
10,2023-03-09,1056770,10714,0,7,0,0,2023-03-10 04:21:03,1046056,7,0.0101,IND,India,Haryana,29.20004,76.332824,[]
11,2023-03-09,312820,4213,0,20,0,0,2023-03-10 04:21:03,308607,20,0.0135,IND,India,Himachal Pradesh,31.927213,77.233081,[]
12,2023-03-09,479513,4785,0,3,0,0,2023-03-10 04:21:03,474728,3,0.0100,IND,India,Jammu and Kashmir,33.75943,76.612638,[]
13,2023-03-09,442579,5331,0,0,0,0,2023-03-10 04:21:03,437248,0,0.0120,IND,India,Jharkhand,23.654536,85.557631,[]
14,2023-03-09,4074536,40312,0,89,1,0,2023-03-10 04:21:03,4034224,88,0.0099,IND,India,Karnataka,14.70518,76.166436,[]
15,2023-03-09,6831358,71589,0,87,1,0,2023-03-10 04:21:03,6759769,86,0.0105,IND,India,Kerala,10.450898,76.405749,[]
16,2023-03-09,29425,231,0,0,0,0,2023-03-10 04:21:03,29194,0,0.0079,IND,India,Ladakh,34.1526,77.5771,[]
17,2023-03-09,1054978,10777,0,8,0,0,2023-03-10 04:21:03,1044201,8,0.0102,IND,India,Madhya Pradesh,23.541513,78.289633,[]
18,2023-03-09,8138129,148424,0,144,1,0,2023-03-10 04:21:03,7989705,143,0.0182,IND,India,Maharashtra,19.449759,76.108221,[]
19,2023-03-09,139924,2149,0,0,0,0,2023-03-10 04:21:03,137775,0,0.0154,IND,India,Manipur,24.738975,93.882541,[]
20,2023-03-09,96788,1625,0,0,0,0,2023-03-10 04:21:03,95163,0,0.0168,IND,India,Meghalaya,25.536934,91.278882,[]
21,2023-03-09,238969,726,0,1,0,0,2023-03-10 04:21:03,238243,1,0.0030,IND,India,Mizoram,23.309381,92.83822,[]
22,2023-03-09,35988,782,0,0,0,0,2023-03-10 04:21:03,35206,0,0.0217,IND,India,Nagaland,26.06702,94.470302,[]
23,2023-03-09,1336717,9205,0,1,0,0,2023-03-10 04:21:03,1327512,1,0.0069,IND,India,Odisha,20.505428,84.418059,[]
24,2023-03-09,175872,1975,0,9,0,0,2023-03-10 04:21:03,173897,9,0.0112,IND,India,Puducherry,11.882658,78.86498,[]
25,2023-03-09,785724,19289,0,1239,0,0,2023-03-10 04:21:03,766435,1239,0.0245,IND,India,Punjab,30.841465000000003,75.40879,[]
26,2023-03-09,1315637,9656,0,7,1,0,2023-03-10 04:21:03,1305981,6,0.0073,IND,India,Rajasthan,26.583423,73.847973,[]
27,2023-03-09,44325,500,0,0,0,0,2023-03-10 04:21:03,43825,0,0.0113,IND,India,Sikkim,27.571671,88.472712,[]
28,2023-03-09,3595123,38049,0,66,0,0,2023-03-10 04:21:03,3557074,66,0.0106,IND,India,Tamil Nadu,11.006091,78.400624,[]
29,2023-03-09,841897,4111,0,67,0,0,2023-03-10 04:21:03,837786,67,0.0049,IND,India,Telangana,18.1124,79.0193,[]
30,2023-03-09,108034,940,0,0,0,0,2023-03-10 04:21:03,107094,0,0.0087,IND,India,Tripura,23.746783,91.743565,[]
31,2023-03-09,0,0,0,0,0,0,2023-03-10 04:21:03,0,0,0.0000,IND,India,Unknown,None,None,[]
32,2023-03-09,2128222,23648,0,1,0,0,2023-03-10 04:21:03,2104574,1,0.0111,IND,India,Uttar Pradesh,26.925425,80.560982,[]
33,2023-03-09,449488,7753,0,1,0,0,2023-03-10 04:21:03,441735,1,0.0172,IND,India,Uttarakhand,30.156447,79.197608,[]
34,2023-03-09,2118857,21533,0,4,0,0,2023-03-10 04:21:03,2097324,4,0.0102,IND,India,West Bengal,23.814082,87.979803,[]
35,2023-03-09,11591,4,0,0,0,0,2023-03-10 04:21:03,11587,0,0.0003,IND,India,Dadra and Nagar Haveli and Daman and Diu,20.194742,73.080901,[]
36,2023-03-09,11415,52,0,0,0,0,2023-03-10 04:21:03,11363,0,0.0046,IND,India,Lakshadweep,13.6999972,72.18333259999999,[]

# Data Cleaning:

In [ ]:
youtube_url = 'http://4.186.26.27:8787/youtube'

In [ ]:
response = requests.get(youtube_url)
df= pd.json_normalize(response.json())

In [ ]:
df.head()

,rank,Youtuber,subscribers,video views,category,Title,uploads,Country,Abbreviation,channel_type,...,subscribers_for_last_30_days,created_year,created_month,created_date,Gross tertiary education enrollment (%),Population,Unemployment rate,Urban_population,Latitude,Longitude
0,1,T-Series,245000000,228000000000,Music,T-Series,20082,India,IN,Music,...,2000000.0,2006.0,Mar,13.0,28.1,1.366418e+09,5.36,471031528.0,20.593684,78.962880
1,2,YouTube Movies,170000000,0,Film & Animation,youtubemovies,1,United States,US,Games,...,NaN,2006.0,Mar,5.0,88.2,3.282395e+08,14.70,270663028.0,37.090240,-95.712891
2,3,MrBeast,166000000,28368841870,Entertainment,MrBeast,741,United States,US,Entertainment,...,8000000.0,2012.0,Feb,20.0,88.2,3.282395e+08,14.70,270663028.0,37.090240,-95.712891
3,4,Cocomelon - Nursery Rhymes,162000000,164000000000,Education,Cocomelon - Nursery Rhymes,966,United States,US,Education,...,1000000.0,2006.0,Sep,1.0,88.2,3.282395e+08,14.70,270663028.0,37.090240,-95.712891
4,5,SET India,159000000,148000000000,Shows,SET India,116536,India,IN,Entertainment,...,1000000.0,2006.0,Sep,20.0,28.1,1.366418e+09,5.36,471031528.0,20.593684,78.962880

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 995 entries, 0 to 994
Data columns (total 28 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   rank                                     995 non-null    int64
 1   Youtuber                                 995 non-null    object
 2   subscribers                              995 non-null    int64
 3   video views                              995 non-null    int64
 4   category                                 949 non-null    object
 5   Title                                    995 non-null    object
 6   uploads                                  995 non-null    int64
 7   Country                                  873 non-null    object
 8   Abbreviation                             873 non-null    object
 9   channel_type                             965 non-null    object
 10  video_views_rank                         994 non-null    float64
 11  country_rank                             879 non-null    float64
 12  channel_type_rank                        962 non-null    float64
 13  video_views_for_the_last_30_days         939 non-null    float64
 14  lowest_monthly_earnings                  995 non-null    float64
 15  highest_monthly_earnings                 995 non-null    float64
 16  lowest_yearly_earnings                   995 non-null    float64
 17  highest_yearly_earnings                  995 non-null    float64
 18  subscribers_for_last_30_days             658 non-null    float64
 19  created_year                             990 non-null    float64
 20  created_month                            990 non-null    object
 21  created_date                             990 non-null    float64
 22  Gross tertiary education enrollment (%)  872 non-null    float64
 23  Population                               872 non-null    float64
 24  Unemployment rate                        872 non-null    float64
 25  Urban_population                         872 non-null    float64
 26  Latitude                                 872 non-null    float64
 27  Longitude                                872 non-null    float64
dtypes: float64(17), int64(4), object(7)
memory usage: 217.8+ KB

In [ ]:
df.isnull().sum()

rank                                         0
Youtuber                                     0
subscribers                                  0
video views                                  0
category                                    46
Title                                        0
uploads                                      0
Country                                    122
Abbreviation                               122
channel_type                                30
video_views_rank                             1
country_rank                               116
channel_type_rank                           33
video_views_for_the_last_30_days            56
lowest_monthly_earnings                      0
highest_monthly_earnings                     0
lowest_yearly_earnings                       0
highest_yearly_earnings                      0
subscribers_for_last_30_days               337
created_year                                 5
created_month                                5
created_date                                 5
Gross tertiary education enrollment (%)    123
Population                                 123
Unemployment rate                          123
Urban_population                           123
Latitude                                   123
Longitude                                  123
dtype: int64

### TASK:
- Perform data cleaning on this youtube dataset.